import { useEffect, useState } from "react";
import { request, setAdminToken } from "../lib/api";

type Product = { _id: string; id: string; name: string; category: string; priceCents: number; material: string; materialGroup: string; gemstones: string; gemShape: string; brand: string; collection: string; description: string; rating: number; image: string; badge?: "New" | "Bestseller" | "Limited"; active: boolean };
type Settings = { businessName: string; email: string; phone: string; address: string; announcement: string };
const blank = (): Omit<Product, "_id"> => ({ id: "", name: "", category: "Rings", priceCents: 0, material: "Silver", materialGroup: "Silver", gemstones: "None", gemShape: "None", brand: "Lumière", collection: "Modern", description: "", rating: 0, image: "", active: true });

export function AdminPage({ onBack }: { onBack: () => void }) {
  const [products, setProducts] = useState<Product[]>([]); const [settings, setSettings] = useState<Settings>({ businessName: "Lumière", email: "", phone: "", address: "", announcement: "" });
  const [draft, setDraft] = useState<Omit<Product, "_id">>(blank()); const [editing, setEditing] = useState<string | null>(null); const [message, setMessage] = useState("Loading admin panel…");
  const [password, setPassword] = useState("");
  const load = async () => { try { const data = await request<{ products: Product[]; settings: Settings }>("/admin/dashboard"); setProducts(data.products); setSettings(data.settings); setMessage(""); } catch (error: any) { setMessage(error.message || "Unable to load the admin panel."); } };
  useEffect(() => { load(); }, []);
  const update = (key: keyof typeof draft, value: string | number | boolean) => setDraft((current) => ({ ...current, [key]: value }));
  const saveProduct = async (event: React.FormEvent) => { event.preventDefault(); try { const body = { ...draft, priceCents: Number(draft.priceCents), rating: Number(draft.rating) }; if (editing) await request(`/admin/products/${editing}`, { method: "PATCH", body: JSON.stringify(body) }); else await request("/admin/products", { method: "POST", body: JSON.stringify(body) }); setDraft(blank()); setEditing(null); setMessage("Product saved."); await load(); } catch (error: any) { setMessage(error.message || "Could not save product."); } };
  const edit = (product: Product) => { const { _id, ...next } = product; setDraft(next); setEditing(_id); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const remove = async (id: string) => { if (!window.confirm("Delete this product?")) return; try { await request(`/admin/products/${id}`, { method: "DELETE" }); await load(); } catch (error: any) { setMessage(error.message || "Could not delete product."); } };
  const saveSettings = async (event: React.FormEvent) => { event.preventDefault(); try { const next = await request<Settings>("/admin/settings", { method: "PUT", body: JSON.stringify(settings) }); setSettings(next); setMessage("Business information saved."); } catch (error: any) { setMessage(error.message || "Could not save business information."); } };
  const unlock = async (event: React.FormEvent) => { event.preventDefault(); try { const data = await request<{ token: string }>("/admin/unlock", { method: "POST", body: JSON.stringify({ password }) }); setAdminToken(data.token); setPassword(""); setMessage("Loading admin panel…"); await load(); } catch (error: any) { setMessage(error.message || "Could not unlock admin access."); } };
  if (message.includes("Administrator access") || message.includes("Authentication")) return <div className="accWrap"><div className="accCard"><h1 className="pageTitle">Admin access required</h1><p className="muted">Sign in with the email configured as <code>ADMIN_EMAIL</code> on the API server.</p><button className="btnOutline" onClick={onBack}>Back to shop</button></div></div>;
  if (message.includes("Additional admin password") || message.includes("Incorrect admin password")) return <div className="accWrap"><div className="accCard"><h1 className="pageTitle">Unlock administration</h1><p className="muted">Enter the separate admin-panel password.</p><form className="accForm accFormNarrow" onSubmit={unlock}><label className="field"><span>Admin password</span><input autoFocus required type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label><button className="btnPrimary" type="submit">Unlock</button></form><button className="btnOutline" onClick={onBack}>Back to shop</button></div></div>;
  return <div className="accWrap"><div className="crumbs muted small">Home / Administration</div><div className="accCard accMainCard" style={{ marginTop: 10 }}><div className="accTopRow"><h1 className="pageTitle">Store administration</h1><button className="btnOutline" onClick={onBack}>Back to shop</button></div>{message && <p className="muted">{message}</p>}
    <form className="accForm accFormWide" onSubmit={saveSettings}><h2>Business information</h2><label className="field"><span>Business name</span><input value={settings.businessName} onChange={(e) => setSettings({ ...settings, businessName: e.target.value })} /></label><label className="field"><span>Contact email</span><input value={settings.email} onChange={(e) => setSettings({ ...settings, email: e.target.value })} /></label><label className="field"><span>Phone</span><input value={settings.phone} onChange={(e) => setSettings({ ...settings, phone: e.target.value })} /></label><label className="field"><span>Address</span><textarea value={settings.address} onChange={(e) => setSettings({ ...settings, address: e.target.value })} /></label><label className="field"><span>Announcement</span><input value={settings.announcement} onChange={(e) => setSettings({ ...settings, announcement: e.target.value })} /></label><button className="btnPrimary" type="submit">Save business info</button></form>
    <form className="accForm accFormWide" style={{ marginTop: 28 }} onSubmit={saveProduct}><h2>{editing ? "Edit product" : "Add product"}</h2><label className="field"><span>Product ID</span><input required value={draft.id} onChange={(e) => update("id", e.target.value)} /></label><label className="field"><span>Name</span><input required value={draft.name} onChange={(e) => update("name", e.target.value)} /></label><label className="field"><span>Price in cents</span><input required min="0" type="number" value={draft.priceCents} onChange={(e) => update("priceCents", e.target.value)} /></label><label className="field"><span>Category</span><input required value={draft.category} onChange={(e) => update("category", e.target.value)} /></label><label className="field"><span>Image URL or path</span><input required value={draft.image} onChange={(e) => update("image", e.target.value)} /></label><label className="field"><span>Description</span><textarea required value={draft.description} onChange={(e) => update("description", e.target.value)} /></label><button className="btnPrimary" type="submit">{editing ? "Save product" : "Add product"}</button>{editing && <button className="btnOutline" type="button" onClick={() => { setEditing(null); setDraft(blank()); }}>Cancel</button>}</form>
    <div style={{ marginTop: 28 }}><h2>Products ({products.length})</h2><div className="accList" style={{ display: "grid", gap: 10 }}>{products.map((product) => <div className="accProfile" key={product._id} style={{ justifyContent: "space-between" }}><div><strong>{product.name}</strong><div className="muted small">{product.id} · €{(product.priceCents / 100).toFixed(2)} · {product.active ? "Active" : "Hidden"}</div></div><div style={{ display: "flex", gap: 8 }}><button className="btnOutline" onClick={() => edit(product)}>Edit</button><button className="btnPrimary" onClick={() => remove(product._id)}>Delete</button></div></div>)}</div></div>
  </div></div>;
}
